language: python
os: linux
python:
- 3.4
- 2.7

env:
  - SIT
  - UAT

script: python3 test_fruits.py

#installation
  #before install
  #install

#script
  #before script
  #script
  
#after script
  #sucess
  #failure

#deploy
  #before deploy
  #depoly
  #after deploy

# list of branches
branches:
  only:
    - master
    - /[upt][a-q]*[t]\b//
  except:
    - opt

jobs:
  fast_finish: true
  # allow_failiures:
    # - python 2.7
  exclude:
    - python: 3.4
      env: SIT

# comments
