language: python
python:
- 3.4
- 2.7

script: python3 test_fruits.py

# list of branches
branches:
  only:
    - master
    - /[upt][a-q]*[t]\b//
  except:
    - opt

env:
  - SIT
  - UAT

matrix:
  include:
    - python: 3.4
    - env: SIT

# comments
