language: python
python:
- 3.4

script: python3 test_fruits.py

# safe list (will build only this list)
branches:
  only:
    - master
    - /[upt][a-q]*[t]\b//

# block list (will not build this list)
branches:
  except:
    - opt

